spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ustozdb
    username: postgres
    password: 123
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
      dialect: org.hibernate.dialect.PostgreSQL81Dialect

server:
  port: 8080
